name: Build & Push Netflix Image to ECR
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: "149142082303.dkr.ecr.ap-south-1.amazonaws.com/netflix"
  IMAGE_TAG: "${{ github.run_number }}"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        run: |
          set -e
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 149142082303.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build --no-cache -t "${ECR_REPOSITORY}:${IMAGE_TAG}" .

      - name: Push Image to ECR
        run: |
          docker push "${ECR_REPOSITORY}:${IMAGE_TAG}"

      - name: Pull and run
        run: |
          docker run -dit "${ECR_REPOSITORY}:${IMAGE_TAG}"

