name: Build & Push Netflix Image to ECR
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: "public.ecr.aws/b4h3v1j9/netflix"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set build number tag
        id: tags
        run: |
          echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          set -e
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b4h3v1j9

      - name: Build Docker Image
        run: |
          docker build -t "${ECR_REPOSITORY}:${IMAGE_TAG}" .

      - name: Push Image to ECR
        run: |
          docker push "${ECR_REPOSITORY}:${IMAGE_TAG}"
